### ISSUE TITLE
I have some problem with download this gem

### ISSUE THREAD

**Issue by grzegorzkoziolek** [1990prashant/solidus_payu_integration#1]
Problem with repo
### On docker

Fetching git://github.com/pkumarmis/solidus_payu_integration.git
sh: git: not found

Retrying `git clone 'git://github.com/pkumarmis/solidus_payu_integration.git' "/usr/local/bundle/cache/bundler/git/solidus_payu_integration-d954780016b6154dafd4486edce96acf1015adb5" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/pkumarmis/solidus_payu_integration.git' "/usr/local/bundle/cache/bundler/git/solidus_payu_integration-d954780016b6154dafd4486edce96acf1015adb5" --bare --no-hardlinks --quiet` in directory /app has failed.sh: git: not found

Retrying `git clone 'git://github.com/pkumarmis/solidus_payu_integration.git' "/usr/local/bundle/cache/bundler/git/solidus_payu_integration-d954780016b6154dafd4486edce96acf1015adb5" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/pkumarmis/solidus_payu_integration.git' "/usr/local/bundle/cache/bundler/git/solidus_payu_integration-d954780016b6154dafd4486edce96acf1015adb5" --bare --no-hardlinks --quiet` in directory /app has failed.sh: git: not found

Retrying `git clone 'git://github.com/pkumarmis/solidus_payu_integration.git' "/usr/local/bundle/cache/bundler/git/solidus_payu_integration-d954780016b6154dafd4486edce96acf1015adb5" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/pkumarmis/solidus_payu_integration.git' "/usr/local/bundle/cache/bundler/git/solidus_payu_integration-d954780016b6154dafd4486edce96acf1015adb5" --bare --no-hardlinks --quiet` in directory /app has failed.sh: git: not found

Git error: command `git clone
'git://github.com/pkumarmis/solidus_payu_integration.git'
"/usr/local/bundle/cache/bundler/git/solidus_payu_integration-d954780016b6154dafd4486edce96acf1015adb5"
--bare --no-hardlinks --quiet` in directory /app has failed.
ERROR: Service 'website' failed to build: The command '/bin/sh -c bundle install --binstubs' returned a non-zero code: 11

**Comment by 1990prashant** [comment]
Please use git://github.com/1990prashant/solidus_payu_integration.git url.
